.TH "src Directory Reference" 3 "Mon Oct 9 2017" "Version 0.1" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBslice\&.c\fP"
.br
.ti -1c
.RI "file \fBvector\&.c\fP"
.br
.ti -1c
.RI "file \fBvector\&.h\fP"
.br
.in -1c
