.TH "tests/check_vector.c" 3 "Fri Oct 6 2017" "Version 0.1" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/check_vector.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <check\&.h>\fP
.br
\fC#include '\&.\&./src/vector\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAPACITY\fP   90000"
.br
.ti -1c
.RI "#define \fBMOD\fP   17"
.br
.ti -1c
.RI "#define \fBRANDOM\fP   1300000"
.br
.ti -1c
.RI "#define \fBN\fP   10000"
.br
.ti -1c
.RI "#define \fBDEN\fP   30000\&.0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTART_TEST\fP (int_vector)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (float_vector)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (string_vector)"
.br
.ti -1c
.RI "END_TEST Suite * \fBvector_suite\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAPACITY   90000"

.SS "#define DEN   30000\&.0"

.SS "#define MOD   17"

.SS "#define N   10000"

.SS "#define RANDOM   1300000"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "START_TEST (int_vector)"

.SS "END_TEST START_TEST (float_vector)"

.SS "END_TEST START_TEST (string_vector)"

.SS "END_TEST Suite* vector_suite ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
