.TH "md_README" 3 "Sun Oct 8 2017" "Version 0.1" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README\fBVector\fP 
 \- \fBA contiguous growable generic type array in C programming language\&.\fP
.PP
\fBVector\fP supports amortized constant time insertion and removal of elements , as well as constant time access\&.
.PP
C doesn’t allow data types to be passed as parameters\&. That means a generic container needs to manually manage memory in terms of the client element size, not client data type\&. You can do generic prommaming in c, without to use macros\&.
.PP
\fBVector\fP is a small standard library and \fCan easy-to-use C API\fP
.PP
The object provided by the \fBVector\fP library is an array type container that:
.PP
.IP "1." 4
It only must contain addresses of HEAP\&. The insertion must be done by calling the Memory Manager, that is: any new insertion will have to be done with pointers to HEAP\&.
.IP "2." 4
Resides in contiguous memory, accessible by arithmetic of pointers
.IP "3." 4
It is generic: it supports any types: we identifie the information not by its type, but by its size
.IP "4." 4
The object resides in HEAP
.IP "5." 4
The object is self-expanding: doubles its capacity automatically if the insertion of a new element requires it
.IP "6." 4
The library provides insertion of items from file\&.
.PP
.PP
The contract is:
.PP
.IP "1." 4
Insert only references to HEAP
.IP "2." 4
Who calls the Memory Manager, free the direction stored in the pointer\&.
.PP
.PP
If we follow the rules, there will be no problem: neither memory leak, neither corruption memory\&.
.PP
\fBExample\fP
.PP
.PP
.nf
        int structs_len = 10;

        // The client calls Memory Manager
        struct st_ex *structs = calloc(structs_len, sizeof(struct st_ex));
        structs[0] = (struct st_ex) {"mp3 player", 299\&.0f};
        structs[1] = (struct st_ex) {"plasma tv", 2200\&.0f};
        structs[2] = (struct st_ex) {"notebook", 1300\&.0f};
        structs[3] = (struct st_ex) {"smartphone", 499\&.99f};
        structs[4] = (struct st_ex) {"mp3 player", 600\&.0f};
        structs[5] = (struct st_ex) {"mp3 player", 451\&.0f};
        structs[6] = (struct st_ex) {"mp4 player", 7211\&.0f};
        structs[7] = (struct st_ex) {"dvd player", 150\&.0f};
        structs[8] = (struct st_ex) {"mp3 ply v", 631\&.0f};
        structs[9] = (struct st_ex) {"matches", 0\&.2f };

        //Constructor
        vector_t *struc = vector_Init(structs_len,
                                    sizeof(struct st_ex),
                                    struct_cmp_by_product);

        size_t i;
        v_stat status;

        for(i = 0; i < structs_len; i++)
            vector_Insert(struc, &structs[i]);

/*
 *         struct st_ex buy = {"matches", 32\&.0f}
 *         vector_Insert(struc, &pepito);
 *         It will generate a warning\&. 'buy' is in the stack
 */


    /***************************************************************
     *
     *                          STRUCT SEARCHING: Filter, Has, Pattern
     *
     * *************************************************************/


        puts("*** Struct searching (product)\&.\&.\&. ordered (by price)");

        vector_t *searched = vector_Init(structs_len,
                                            sizeof(struct st_ex),
                                            struct_cmp_by_price);

        char *found = "mp3 player";

        // Binary Search of an item\&. It copies in 'searched' all the items that
        // match with 'found'
        status = vector_Filter(struc, found, searched);

        switch(status) {
            case V_OK :  print_struct_Vector(searched,
                                                                vector_Len(searched));
                                 break;
            case V_ERR_IS_EMPTY :
                                printf("Vector is Empty\n");
                                break;
            case V_ERR_VALUE_NOT_FOUND :
                                printf("Item %s has not been found\n", found);
                                break;
            case V_ERR_INVALID_ARGUMENT:
                                printf("Invalid arguments\n");
                                break;
        }

        // The client frees its pointers to HEAP
        free(structs);

        // The library frees its pointers to HEAP
        struc->Destroy(struc);
        searched->Destroy_slice(searched);

        return 0;
.fi
.PP
 \fBHow to Install\fP Prerequisites for installation: 
.PP
.nf
gcc
make

.fi
.PP
.PP
\fBPrerequisites for Running Tests:\fP 
.PP
.nf
Check

.fi
.PP
.PP
Steps to run tests: 
.PP
.nf
Download a release from github.

Extract the archive and cd into the extracted directory.

Run this command

.fi
.PP
.PP
\fC\&./configure\fP 
.PP
.nf
If the above command runs successfully, run this

.fi
.PP
.PP
\fCmake\fP 
.PP
.nf
Again, if the above command runs successfully, run this

.fi
.PP
.PP
\fCmake install\fP 
.PP
.nf
If you want to run tests(Optional) to make sure everything works fine, run this

.fi
.PP
.PP
\fCmake check\fP
.PP
Now, you can include heade file \fB\fBvector\&.h\fP\fP
.PP
For linking the vector library, gcc command would look like, \fCgcc -L/usr/local/lib/vector your_cprog\&.c -lvector\fP
.PP
where \fCyour_cprog\&.c\fP is your c program using \fBVector\fP library\&.
.PP
By default vector library is installed into \fC/usr/local/lib/vector\fP unless you have changed the prefix while configuring\&.
.PP
If you find any bugs or have any feature requests, please create an Issue on Github\&. 
