.TH "st_ex" 3 "Sun Oct 8 2017" "Version 0.1" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_ex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBproduct\fP [16]"
.br
.ti -1c
.RI "float \fBprice\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float st_ex::price"

.SS "char st_ex::product[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
